## Etude de vins

### Faire un rapport statistique pour chaque années

### Etude comparative des productions de vin par département et par type de vin de 2015 à 2018

In [38]:
import pandas as pd
import numpy as np

In [39]:
production2015 = pd.read_excel("C:/Users/Dell/Desktop/td_python/data/2015-stats-recolte.xls")
production2015.head()

,DEPARTEMENTS,Nb déclarations prod,Sup totale vignes (ha),Sup vignes AOP (ha),Sup vignes cognac - armagniac (ha),Sup vignes IGP (ha),Sup vignes VSIG (ha),Qt AOP Blanc (hl),Qt AOP Rouge (hl),Qt AOP Rosé (hl),...,Qt IGP Blanc (hl),Qt IGP Rouge (hl),Qt IGP Rosé (hl),Qt IGP VCI (hl),Qt VSIG Blanc (hl),Qt VSIG Rouge (hl),Qt VSIG Rosé (hl),Qt Cognac ou Armagnec (hl),Prod commercialisable (hl),Prod non commercialisable (hl)
0,01 AIN,382,758.4526,551.8399,0.0,17.2905,189.3222,12323.03,2897.22,12658.40,...,442.71,79.85,91.05,0.0,2977.20,1672.51,5846.95,0.0,38988.92,244.40
1,02 AISNE,804,2441.2928,2435.8592,0.0,0.0000,5.4336,164777.06,0.00,0.00,...,0.00,0.00,0.00,0.0,349.39,7.70,0.00,0.0,165134.15,14343.05
2,03 ALLIER,209,647.2769,553.2800,0.0,7.9338,86.0631,7394.03,12766.96,3381.52,...,0.00,100.34,0.00,0.0,547.71,653.24,1580.05,0.0,26423.85,679.28
3,04 ALPES-HTE-PR,78,674.1128,282.2810,0.0,319.4883,72.3435,1609.25,5278.29,6582.89,...,2914.90,6129.07,13147.98,0.0,212.91,878.61,3714.17,0.0,40468.07,1264.55
4,05 ALPES-HAUTES,110,115.6571,0.0000,0.0,100.9580,14.6991,0.00,0.00,0.00,...,878.30,1918.99,1055.43,0.0,88.15,226.35,6.80,0.0,4174.02,281.51

In [40]:
production2015.dtypes

DEPARTEMENTS                           object
Nb déclarations prod                    int64
Sup totale vignes (ha)                float64
Sup vignes AOP (ha)                   float64
Sup vignes cognac - armagniac (ha)    float64
Sup vignes IGP (ha)                   float64
Sup vignes VSIG (ha)                  float64
Qt AOP Blanc (hl)                     float64
Qt AOP Rouge (hl)                     float64
Qt AOP Rosé (hl)                      float64
Qt AOP VSI/VCI (hl)                   float64
Qt IGP Blanc (hl)                     float64
Qt IGP Rouge (hl)                     float64
Qt IGP Rosé (hl)                      float64
Qt IGP VCI (hl)                       float64
Qt VSIG Blanc (hl)                    float64
Qt VSIG Rouge (hl)                    float64
Qt VSIG Rosé (hl)                     float64
Qt Cognac ou Armagnec (hl)            float64
Prod commercialisable (hl)            float64
Prod non commercialisable (hl)        float64
dtype: object

In [41]:
production2016 = pd.read_excel("C:/Users/Dell/Desktop/td_python/data/2016-stats-recolte.xls")
production2016.head()

,DEPARTEMENTS,Nb déclarations prod,Sup totale vignes (ha),Sup vignes AOP (ha),Sup vignes cognac - armagniac (ha),Sup vignes IGP (ha),Sup vignes VSIG (ha),Qt AOP Blanc (hl),Qt AOP Rouge (hl),Qt AOP Rosé (hl),Qt AOP VSI/VCI (hl),Qt IGP Blanc (hl),Qt IGP Rouge (hl),Qt IGP Rosé (hl),Qt VSIG Blanc (hl),Qt VSIG Rouge (hl),Qt VSIG Rosé (hl),Qt Cognac ou Armagnec (hl),Prod commercialisable (hl),Prod non commercialisable (hl)
0,01 AIN,321,777.9424,540.2316,0.0,19.9388,217.7720,13283.93,2992.10,13615.22,0.0,744.54,136.69,192.00,4635.04,2137.33,7383.05,0.0,45119.90,314.83
1,02 AISNE,780,2428.5932,2424.3949,0.0,0.0000,4.1983,148045.03,0.00,0.00,0.0,0.00,0.00,0.00,150.10,0.00,0.00,0.0,148195.13,9149.60
2,03 ALLIER,134,609.5174,539.3517,0.0,9.3103,60.8554,6569.56,12854.80,3211.12,0.0,193.00,99.09,0.00,354.33,522.50,1159.40,0.0,24963.80,536.62
3,04 ALPES-HTE-PR,69,777.9662,285.6060,0.0,444.4527,47.9075,1580.08,4834.69,6915.95,0.0,2916.39,6680.06,15948.43,393.28,826.50,2444.00,0.0,42539.38,1177.17
4,05 ALPES-HAUTES,110,137.7478,0.0000,0.0,105.2704,32.4774,0.00,0.00,0.00,0.0,1542.35,2564.44,1465.25,105.22,215.45,6.55,0.0,5899.26,408.74

In [42]:
production2017 = pd.read_excel("C:/Users/Dell/Desktop/td_python/data/2017-stats-recolte.xls")
production2017.head()

,DEPARTEMENTS,Nb déclarations prod,Sup totale vignes (ha),Sup vignes AOP (ha),Sup vignes cognac - armagniac (ha),Sup vignes IGP (ha),Sup vignes VSIG (ha),Qt AOP Blanc (hl),Qt AOP Rouge (hl),Qt AOP Rosé (hl),Qt AOP VSI/VCI (hl),Qt IGP Blanc (hl),Qt IGP Rouge (hl),Qt IGP Rosé (hl),Qt VSIG Blanc (hl),Qt VSIG Rouge (hl),Qt VSIG Rosé (hl),Qt Cognac ou Armagnec (hl),Prod commercialisable (hl),Autres production (hl)
0,01 AIN,284,749.5860,537.0579,0.0,20.5849,191.9432,9457.75,2495.30,8143.25,0.0,595.25,131.60,66.20,3675.53,1639.45,3224.92,0.0,29429.25,186.12
1,02 AISNE,818,2523.6857,2519.2927,0.0,0.0000,4.3930,151065.59,0.00,0.00,0.0,0.00,0.00,0.00,158.60,0.00,0.00,0.0,151224.19,1341.88
2,03 ALLIER,109,610.2514,557.7564,0.0,7.1575,45.3375,3591.34,8033.47,2184.96,0.0,0.00,111.53,0.00,198.57,246.70,417.05,0.0,14783.62,282.28
3,04 ALPES DE HAUTES-PROVENCE,72,700.5272,293.9354,0.0,356.9192,49.6726,1251.21,3386.12,7209.38,0.0,2559.50,4380.06,9771.54,292.32,1134.95,2133.50,0.0,32118.58,934.01
4,05 HAUTES-ALPES,94,114.6767,0.0000,0.0,105.3222,9.3545,0.00,0.00,0.00,0.0,383.50,982.64,596.59,21.88,77.50,1.10,0.0,2063.21,131.46

In [43]:
production2017=production2017.set_index('DEPARTEMENTS')
production2017.head(1)

,Nb déclarations prod,Sup totale vignes (ha),Sup vignes AOP (ha),Sup vignes cognac - armagniac (ha),Sup vignes IGP (ha),Sup vignes VSIG (ha),Qt AOP Blanc (hl),Qt AOP Rouge (hl),Qt AOP Rosé (hl),Qt AOP VSI/VCI (hl),Qt IGP Blanc (hl),Qt IGP Rouge (hl),Qt IGP Rosé (hl),Qt VSIG Blanc (hl),Qt VSIG Rouge (hl),Qt VSIG Rosé (hl),Qt Cognac ou Armagnec (hl),Prod commercialisable (hl),Autres production (hl)
DEPARTEMENTS,,,,,,,,,,,,,,,,,,,
01 AIN,284,749.586,537.0579,0.0,20.5849,191.9432,9457.75,2495.3,8143.25,0.0,595.25,131.6,66.2,3675.53,1639.45,3224.92,0.0,29429.25,186.12

In [44]:
production2016=production2016.set_index('DEPARTEMENTS')
production2016.head(1)

,Nb déclarations prod,Sup totale vignes (ha),Sup vignes AOP (ha),Sup vignes cognac - armagniac (ha),Sup vignes IGP (ha),Sup vignes VSIG (ha),Qt AOP Blanc (hl),Qt AOP Rouge (hl),Qt AOP Rosé (hl),Qt AOP VSI/VCI (hl),Qt IGP Blanc (hl),Qt IGP Rouge (hl),Qt IGP Rosé (hl),Qt VSIG Blanc (hl),Qt VSIG Rouge (hl),Qt VSIG Rosé (hl),Qt Cognac ou Armagnec (hl),Prod commercialisable (hl),Prod non commercialisable (hl)
DEPARTEMENTS,,,,,,,,,,,,,,,,,,,
01 AIN,321,777.9424,540.2316,0.0,19.9388,217.772,13283.93,2992.1,13615.22,0.0,744.54,136.69,192.0,4635.04,2137.33,7383.05,0.0,45119.9,314.83

In [45]:
production2015=production2015.set_index('DEPARTEMENTS')
production2015.head(1)

,Nb déclarations prod,Sup totale vignes (ha),Sup vignes AOP (ha),Sup vignes cognac - armagniac (ha),Sup vignes IGP (ha),Sup vignes VSIG (ha),Qt AOP Blanc (hl),Qt AOP Rouge (hl),Qt AOP Rosé (hl),Qt AOP VSI/VCI (hl),Qt IGP Blanc (hl),Qt IGP Rouge (hl),Qt IGP Rosé (hl),Qt IGP VCI (hl),Qt VSIG Blanc (hl),Qt VSIG Rouge (hl),Qt VSIG Rosé (hl),Qt Cognac ou Armagnec (hl),Prod commercialisable (hl),Prod non commercialisable (hl)
DEPARTEMENTS,,,,,,,,,,,,,,,,,,,,
01 AIN,382,758.4526,551.8399,0.0,17.2905,189.3222,12323.03,2897.22,12658.4,0.0,442.71,79.85,91.05,0.0,2977.2,1672.51,5846.95,0.0,38988.92,244.4

In [46]:
production2015.groupby('DEPARTEMENTS').describe()

                  Nb déclarations prod                                       \
                                  count    mean std     min     25%     50%
DEPARTEMENTS
01 AIN                              1.0   382.0 NaN   382.0   382.0   382.0
02 AISNE                            1.0   804.0 NaN   804.0   804.0   804.0
03 ALLIER                           1.0   209.0 NaN   209.0   209.0   209.0
04 ALPES-HTE-PR                     1.0    78.0 NaN    78.0    78.0    78.0
05 ALPES-HAUTES                     1.0   110.0 NaN   110.0   110.0   110.0
06 ALPES-Mmes                       1.0    31.0 NaN    31.0    31.0    31.0
07 ARDECHE                          1.0  1825.0 NaN  1825.0  1825.0  1825.0
08 ARDENNES                         1.0     2.0 NaN     2.0     2.0     2.0
09 ARIEGE                           1.0    42.0 NaN    42.0    42.0    42.0
10 AUBE                             1.0  2647.0 NaN  2647.0  2647.0  2647.0
11 AUDE                             1.0  5535.0 NaN  5535.0  5535.0  5535.0
12 AVEYRON                          1.0   150.0 NaN   150.0   150.0   150.0
13 BOUCHES-DU-R                     1.0  1166.0 NaN  1166.0  1166.0  1166.0
14 CALVADOS                         1.0     1.0 NaN     1.0     1.0     1.0
15 CANTAL                           1.0     9.0 NaN     9.0     9.0     9.0
16 CHARENTE                         1.0  3161.0 NaN  3161.0  3161.0  3161.0
17 CHARENTE-MAR                     1.0  4232.0 NaN  4232.0  4232.0  4232.0
18 CHER                             1.0   608.0 NaN   608.0   608.0   608.0
19 CORREZE                          1.0   344.0 NaN   344.0   344.0   344.0
21 COTE D'OR                        1.0  1556.0 NaN  1556.0  1556.0  1556.0
24 DORDOGNE                         1.0  1625.0 NaN  1625.0  1625.0  1625.0
25 DOUBS                            1.0    77.0 NaN    77.0    77.0    77.0
26 DROME                            1.0  1729.0 NaN  1729.0  1729.0  1729.0
28 EURE-ET-LOIR                     1.0     1.0 NaN     1.0     1.0     1.0
2A CORSE SUD                        1.0    46.0 NaN    46.0    46.0    46.0
2B CORSE(HTE)                       1.0   285.0 NaN   285.0   285.0   285.0
30 GARD                             1.0  4017.0 NaN  4017.0  4017.0  4017.0
31 GARONNE(HTE)                     1.0   299.0 NaN   299.0   299.0   299.0
32 GERS                             1.0  1327.0 NaN  1327.0  1327.0  1327.0
33 GIRONDE                          1.0  6889.0 NaN  6889.0  6889.0  6889.0
...                                 ...     ...  ..     ...     ...     ...
55 MEUSE                            1.0    13.0 NaN    13.0    13.0    13.0
57 MOSELLE                          1.0    61.0 NaN    61.0    61.0    61.0
58 NIEVRE                           1.0   311.0 NaN   311.0   311.0   311.0
59 NORD                             1.0     3.0 NaN     3.0     3.0     3.0
60 OISE                             1.0     2.0 NaN     2.0     2.0     2.0
62 PAS DE CALAIS                    1.0     1.0 NaN     1.0     1.0     1.0
63 PUY-DE-DOME                      1.0   519.0 NaN   519.0   519.0   519.0
64 PYRENEES-AT                      1.0   675.0 NaN   675.0   675.0   675.0
65 PYRENEES(HTE)                    1.0   243.0 NaN   243.0   243.0   243.0
66 PYRENEES-OR                      1.0  2719.0 NaN  2719.0  2719.0  2719.0
67 RHIN(BAS)                        1.0  1828.0 NaN  1828.0  1828.0  1828.0
68 RHIN (HAUT)                      1.0  2355.0 NaN  2355.0  2355.0  2355.0
69 RHONE                            1.0  2605.0 NaN  2605.0  2605.0  2605.0
70 SAONE(HAUTE)                     1.0    92.0 NaN    92.0    92.0    92.0
71 SAONE-ET-L                       1.0  1943.0 NaN  1943.0  1943.0  1943.0
72 SARTHE                           1.0   136.0 NaN   136.0   136.0   136.0
73 SAVOIE                           1.0   591.0 NaN   591.0   591.0   591.0
74 SAVOIE(HTE)                      1.0   103.0 NaN   103.0   103.0   103.0
77 SEINE ET MARNE                   1.0     9.0 NaN     9.0     9.0     9.0
79 SEVRES(DEUX)                     1.0   834.0 NaN   834.0   834.0   834.0
81 TARN                             1.0   652.0 NaN   652.0   652.0   652.0
82 TARN-ET-G                        1.0   445.0 NaN   445.0   445.0   445.0
83 VAR                              1.0  3503.0 NaN  3503.0  3503.0  3503.0
84 VAUCLUSE                         1.0  4023.0 NaN  4023.0  4023.0  4023.0
85 VENDEE                           1.0  1582.0 NaN  1582.0  1582.0  1582.0
86 VIENNE                           1.0  1261.0 NaN  1261.0  1261.0  1261.0
87 VIENNE(HTE)                      1.0     6.0 NaN     6.0     6.0     6.0
88 VOSGES                           1.0    98.0 NaN    98.0    98.0    98.0
89 YONNE                            1.0   947.0 NaN   947.0   947.0   947.0
90 T. de BELFORT                    1.0     2.0 NaN     2.0     2.0     2.0

                                  Sup totale vignes (ha)               \
                      75%     max                  count         mean
DEPARTEMENTS
01 AIN              382.0   382.0                    1.0     758.4526
02 AISNE            804.0   804.0                    1.0    2441.2928
03 ALLIER           209.0   209.0                    1.0     647.2769
04 ALPES-HTE-PR      78.0    78.0                    1.0     674.1128
05 ALPES-HAUTES     110.0   110.0                    1.0     115.6571
06 ALPES-Mmes        31.0    31.0                    1.0      85.9950
07 ARDECHE         1825.0  1825.0                    1.0   10320.8559
08 ARDENNES           2.0     2.0                    1.0       0.1020
09 ARIEGE            42.0    42.0                    1.0      67.4625
10 AUBE            2647.0  2647.0                    1.0    6967.7343
11 AUDE            5535.0  5535.0                    1.0   67810.3697
12 AVEYRON          150.0   150.0                    1.0     403.6896
13 BOUCHES-DU-R    1166.0  1166.0                    1.0   10150.5962
14 CALVADOS           1.0     1.0                    1.0       4.9000
15 CANTAL             9.0     9.0                    1.0       8.2823
16 CHARENTE        3161.0  3161.0                    1.0   39145.4714
17 CHARENTE-MAR    4232.0  4232.0                    1.0   38783.0171
18 CHER             608.0   608.0                    1.0    4190.8625
19 CORREZE          344.0   344.0                    1.0     138.7205
21 COTE D'OR       1556.0  1556.0                    1.0    9528.0702
24 DORDOGNE        1625.0  1625.0                    1.0   11475.9674
25 DOUBS             77.0    77.0                    1.0      22.1579
26 DROME           1729.0  1729.0                    1.0   15995.4161
28 EURE-ET-LOIR       1.0     1.0                    1.0       0.1000
2A CORSE SUD         46.0    46.0                    1.0     886.6359
2B CORSE(HTE)       285.0   285.0                    1.0    4907.6603
30 GARD            4017.0  4017.0                    1.0   52498.4556
31 GARONNE(HTE)     299.0   299.0                    1.0    1546.5985
32 GERS            1327.0  1327.0                    1.0   17710.8953
33 GIRONDE         6889.0  6889.0                    1.0  113645.0889
...                   ...     ...                    ...          ...
55 MEUSE             13.0    13.0                    1.0      40.5987
57 MOSELLE           61.0    61.0                    1.0      95.2150
58 NIEVRE           311.0   311.0                    1.0    1585.1969
59 NORD               3.0     3.0                    1.0       1.4090
60 OISE               2.0     2.0                    1.0       0.3045
62 PAS DE CALAIS      1.0     1.0                    1.0       0.3000
63 PUY-DE-DOME      519.0   519.0                    1.0     465.3301
64 PYRENEES-AT      675.0   675.0                    1.0    2427.1162
65 PYRENEES(HTE)    243.0   243.0                    1.0     467.8503
66 PYRENEES-OR     2719.0  2719.0                    1.0   22533.1746
67 RHIN(BAS)       1828.0  1828.0                    1.0    6636.9876
68 RHIN (HAUT)     2355.0  2355.0                    1.0    8941.6342
69 RHONE           2605.0  2605.0                    1.0   16669.1047
70 SAONE(HAUTE)      92.0    92.0                    1.0     105.2027
71 SAONE-ET-L      1943.0  1943.0                    1.0   12950.5554
72 SARTHE           136.0   136.0                    1.0     204.6090
73 SAVOIE           591.0   591.0                    1.0    1859.6884
74 SAVOIE(HTE)      103.0   103.0                    1.0     248.4760
77 SEINE ET MARNE     9.0     9.0                    1.0      21.5161
79 SEVRES(DEUX)     834.0   834.0                    1.0     945.6915
81 TARN             652.0   652.0                    1.0    6460.2700
82 TARN-ET-G        445.0   445.0                    1.0    1605.9136
83 VAR             3503.0  3503.0                    1.0   27662.6286
84 VAUCLUSE        4023.0  4023.0                    1.0   45877.4184
85 VENDEE          1582.0  1582.0                    1.0    1084.3752
86 VIENNE          1261.0  1261.0                    1.0    1319.7456
87 VIENNE(HTE)        6.0     6.0                    1.0       6.6514
88 VOSGES            98.0    98.0                    1.0      20.6634
89 YONNE            947.0   947.0                    1.0    7566.0483
90 T. de BELFORT      2.0     2.0                    1.0       1.1237

                     ...     Prod commercialisable (hl)              \
                     ...                            75%         max
DEPARTEMENTS         ...
01 AIN               ...                       38988.92    38988.92
02 AISNE             ...                      165134.15   165134.15
03 ALLIER            ...                       26423.85    26423.85
04 ALPES-HTE-PR      ...                       40468.07    40468.07
05 ALPES-HAUTES      ...                        4174.02     4174.02
06 ALPES-Mmes        ...                        2180.13     2180.13
07 ARDECHE           ...                      509635.09   509635.09
08 ARDENNES          ...                           5.10        5.10
09 ARIEGE            ...                        2493.63     2493.63
10 AUBE              ...                      480294.45   480294.45
11 AUDE              ...                     3817261.01  3817261.01
12 AVEYRON           ...                       13859.25    13859.25
13 BOUCHES-DU-R      ...                      599704.25   599704.25
14 CALVADOS          ...                         183.25      183.25
15 CANTAL            ...                         208.34      208.34
16 CHARENTE          ...                     4780830.41  4780830.41
17 CHARENTE-MAR      ...                     4850182.47  4850182.47
18 CHER              ...                      234272.53   234272.53
19 CORREZE           ...                        3335.07     3335.07
21 COTE D'OR         ...                      387471.63   387471.63
24 DORDOGNE          ...                      506360.37   506360.37
25 DOUBS             ...                         641.39      641.39
26 DROME             ...                      752619.82   752619.82
28 EURE-ET-LOIR      ...                           6.80        6.80
2A CORSE SUD         ...                       34054.40    34054.40
2B CORSE(HTE)        ...                      344341.75   344341.75
30 GARD              ...                     3285108.69  3285108.69
31 GARONNE(HTE)      ...                       76158.18    76158.18
32 GERS              ...                     1698581.56  1698581.56
33 GIRONDE           ...                     5549976.99  5549976.99
...                  ...                            ...         ...
55 MEUSE             ...                        1625.08     1625.08
57 MOSELLE           ...                        4757.37     4757.37
58 NIEVRE            ...                       86778.99    86778.99
59 NORD              ...                          43.80       43.80
60 OISE              ...                          16.55       16.55
62 PAS DE CALAIS     ...                           3.50        3.50
63 PUY-DE-DOME       ...                       18325.69    18325.69
64 PYRENEES-AT       ...                       99384.87    99384.87
65 PYRENEES(HTE)     ...                       11021.20    11021.20
66 PYRENEES-OR       ...                      815113.22   815113.22
67 RHIN(BAS)         ...                      436460.77   436460.77
68 RHIN (HAUT)       ...                      552420.97   552420.97
69 RHONE             ...                      668626.40   668626.40
70 SAONE(HAUTE)      ...                        3407.58     3407.58
71 SAONE-ET-L        ...                      708935.45   708935.45
72 SARTHE            ...                        6694.44     6694.44
73 SAVOIE            ...                      109240.47   109240.47
74 SAVOIE(HTE)       ...                       11437.34    11437.34
77 SEINE ET MARNE    ...                        1554.05     1554.05
79 SEVRES(DEUX)      ...                       52183.30    52183.30
81 TARN              ...                      347217.16   347217.16
82 TARN-ET-G         ...                       84012.99    84012.99
83 VAR               ...                     1416091.82  1416091.82
84 VAUCLUSE          ...                     2091022.09  2091022.09
85 VENDEE            ...                       54571.33    54571.33
86 VIENNE            ...                       65875.92    65875.92
87 VIENNE(HTE)       ...                         182.80      182.80
88 VOSGES            ...                         552.68      552.68
89 YONNE             ...                      450489.60   450489.60
90 T. de BELFORT     ...                          17.70       17.70

                  Prod non commercialisable (hl)                            \
                                           count       mean std        min
DEPARTEMENTS
01 AIN                                       1.0     244.40 NaN     244.40
02 AISNE                                     1.0   14343.05 NaN   14343.05
03 ALLIER                                    1.0     679.28 NaN     679.28
04 ALPES-HTE-PR                              1.0    1264.55 NaN    1264.55
05 ALPES-HAUTES                              1.0     281.51 NaN     281.51
06 ALPES-Mmes                                1.0      64.60 NaN      64.60
07 ARDECHE                                   1.0   11308.57 NaN   11308.57
08 ARDENNES                                  1.0       0.00 NaN       0.00
09 ARIEGE                                    1.0      50.73 NaN      50.73
10 AUBE                                      1.0   34376.94 NaN   34376.94
11 AUDE                                      1.0   67500.32 NaN   67500.32
12 AVEYRON                                   1.0     363.69 NaN     363.69
13 BOUCHES-DU-R                              1.0   23154.71 NaN   23154.71
14 CALVADOS                                  1.0       0.00 NaN       0.00
15 CANTAL                                    1.0       3.80 NaN       3.80
16 CHARENTE                                  1.0    8247.67 NaN    8247.67
17 CHARENTE-MAR                              1.0   12430.23 NaN   12430.23
18 CHER                                      1.0     742.34 NaN     742.34
19 CORREZE                                   1.0       0.00 NaN       0.00
21 COTE D'OR                                 1.0    4575.90 NaN    4575.90
24 DORDOGNE                                  1.0   12286.03 NaN   12286.03
25 DOUBS                                     1.0      10.80 NaN      10.80
26 DROME                                     1.0   21016.90 NaN   21016.90
28 EURE-ET-LOIR                              1.0       0.00 NaN       0.00
2A CORSE SUD                                 1.0     949.65 NaN     949.65
2B CORSE(HTE)                                1.0    8924.39 NaN    8924.39
30 GARD                                      1.0   84293.41 NaN   84293.41
31 GARONNE(HTE)                              1.0    2014.10 NaN    2014.10
32 GERS                                      1.0   30517.98 NaN   30517.98
33 GIRONDE                                   1.0  122289.52 NaN  122289.52
...                                          ...        ...  ..        ...
55 MEUSE                                     1.0      87.28 NaN      87.28
57 MOSELLE                                   1.0      19.49 NaN      19.49
58 NIEVRE                                    1.0      77.31 NaN      77.31
59 NORD                                      1.0       0.00 NaN       0.00
60 OISE                                      1.0       0.00 NaN       0.00
62 PAS DE CALAIS                             1.0       0.00 NaN       0.00
63 PUY-DE-DOME                               1.0     214.36 NaN     214.36
64 PYRENEES-AT                               1.0    1295.28 NaN    1295.28
65 PYRENEES(HTE)                             1.0     257.16 NaN     257.16
66 PYRENEES-OR                               1.0   27596.48 NaN   27596.48
67 RHIN(BAS)                                 1.0   10447.45 NaN   10447.45
68 RHIN (HAUT)                               1.0    7507.33 NaN    7507.33
69 RHONE                                     1.0   36548.58 NaN   36548.58
70 SAONE(HAUTE)                              1.0      31.00 NaN      31.00
71 SAONE-ET-L                                1.0   18244.21 NaN   18244.21
72 SARTHE                                    1.0     176.73 NaN     176.73
73 SAVOIE                                    1.0    1766.67 NaN    1766.67
74 SAVOIE(HTE)                               1.0      65.39 NaN      65.39
77 SEINE ET MARNE                            1.0     161.67 NaN     161.67
79 SEVRES(DEUX)                              1.0     708.96 NaN     708.96
81 TARN                                      1.0    7605.75 NaN    7605.75
82 TARN-ET-G                                 1.0    2054.28 NaN    2054.28
83 VAR                                       1.0   58548.77 NaN   58548.77
84 VAUCLUSE                                  1.0   61347.06 NaN   61347.06
85 VENDEE                                    1.0    1398.72 NaN    1398.72
86 VIENNE                                    1.0     731.26 NaN     731.26
87 VIENNE(HTE)                               1.0      15.00 NaN      15.00
88 VOSGES                                    1.0       0.00 NaN       0.00
89 YONNE                                     1.0    9430.14 NaN    9430.14
90 T. de BELFORT                             1.0       0.60 NaN       0.60


                         25%        50%        75%        max
DEPARTEMENTS
01 AIN                244.40     244.40     244.40     244.40
02 AISNE            14343.05   14343.05   14343.05   14343.05
03 ALLIER             679.28     679.28     679.28     679.28
04 ALPES-HTE-PR      1264.55    1264.55    1264.55    1264.55
05 ALPES-HAUTES       281.51     281.51     281.51     281.51
06 ALPES-Mmes          64.60      64.60      64.60      64.60
07 ARDECHE          11308.57   11308.57   11308.57   11308.57
08 ARDENNES             0.00       0.00       0.00       0.00
09 ARIEGE              50.73      50.73      50.73      50.73
10 AUBE             34376.94   34376.94   34376.94   34376.94
11 AUDE             67500.32   67500.32   67500.32   67500.32
12 AVEYRON            363.69     363.69     363.69     363.69
13 BOUCHES-DU-R     23154.71   23154.71   23154.71   23154.71
14 CALVADOS             0.00       0.00       0.00       0.00
15 CANTAL               3.80       3.80       3.80       3.80
16 CHARENTE          8247.67    8247.67    8247.67    8247.67
17 CHARENTE-MAR     12430.23   12430.23   12430.23   12430.23
18 CHER               742.34     742.34     742.34     742.34
19 CORREZE              0.00       0.00       0.00       0.00
21 COTE D'OR         4575.90    4575.90    4575.90    4575.90
24 DORDOGNE         12286.03   12286.03   12286.03   12286.03
25 DOUBS               10.80      10.80      10.80      10.80
26 DROME            21016.90   21016.90   21016.90   21016.90
28 EURE-ET-LOIR         0.00       0.00       0.00       0.00
2A CORSE SUD          949.65     949.65     949.65     949.65
2B CORSE(HTE)        8924.39    8924.39    8924.39    8924.39

In [47]:
production2016.groupby('DEPARTEMENTS').describe()

                  Nb déclarations prod                                       \
                                  count    mean std     min     25%     50%
DEPARTEMENTS
01 AIN                              1.0   321.0 NaN   321.0   321.0   321.0
02 AISNE                            1.0   780.0 NaN   780.0   780.0   780.0
03 ALLIER                           1.0   134.0 NaN   134.0   134.0   134.0
04 ALPES-HTE-PR                     1.0    69.0 NaN    69.0    69.0    69.0
05 ALPES-HAUTES                     1.0   110.0 NaN   110.0   110.0   110.0
06 ALPES-Mmes                       1.0    43.0 NaN    43.0    43.0    43.0
07 ARDECHE                          1.0  1751.0 NaN  1751.0  1751.0  1751.0
09 ARIEGE                           1.0    29.0 NaN    29.0    29.0    29.0
10 AUBE                             1.0  2582.0 NaN  2582.0  2582.0  2582.0
11 AUDE                             1.0  5408.0 NaN  5408.0  5408.0  5408.0
12 AVEYRON                          1.0   143.0 NaN   143.0   143.0   143.0
13 BOUCHES-DU-R                     1.0  1133.0 NaN  1133.0  1133.0  1133.0
14 CALVADOS                         1.0     1.0 NaN     1.0     1.0     1.0
15 CANTAL                           1.0     6.0 NaN     6.0     6.0     6.0
16 CHARENTE                         1.0  2844.0 NaN  2844.0  2844.0  2844.0
17 CHARENTE-MAR                     1.0  3877.0 NaN  3877.0  3877.0  3877.0
18 CHER                             1.0   550.0 NaN   550.0   550.0   550.0
19 CORREZE                          1.0   239.0 NaN   239.0   239.0   239.0
21 COTE D'OR                        1.0  1490.0 NaN  1490.0  1490.0  1490.0
24 DORDOGNE                         1.0  1296.0 NaN  1296.0  1296.0  1296.0
25 DOUBS                            1.0    57.0 NaN    57.0    57.0    57.0
26 DROME                            1.0  1635.0 NaN  1635.0  1635.0  1635.0
28 EURE-ET-LOIR                     1.0     1.0 NaN     1.0     1.0     1.0
2A CORSE SUD                        1.0    47.0 NaN    47.0    47.0    47.0
2B CORSE(HTE)                       1.0   233.0 NaN   233.0   233.0   233.0
30 GARD                             1.0  3924.0 NaN  3924.0  3924.0  3924.0
31 GARONNE(HTE)                     1.0   252.0 NaN   252.0   252.0   252.0
32 GERS                             1.0  1240.0 NaN  1240.0  1240.0  1240.0
33 GIRONDE                          1.0  6662.0 NaN  6662.0  6662.0  6662.0
34 HERAULT                          1.0  8844.0 NaN  8844.0  8844.0  8844.0
...                                 ...     ...  ..     ...     ...     ...
54 MEURTHE-&-M                      1.0    57.0 NaN    57.0    57.0    57.0
55 MEUSE                            1.0     7.0 NaN     7.0     7.0     7.0
57 MOSELLE                          1.0    37.0 NaN    37.0    37.0    37.0
58 NIEVRE                           1.0   257.0 NaN   257.0   257.0   257.0
59 NORD                             1.0     2.0 NaN     2.0     2.0     2.0
60 OISE                             1.0     1.0 NaN     1.0     1.0     1.0
62 PAS-DE-CALAIS                    1.0     1.0 NaN     1.0     1.0     1.0
63 PUY-DE-DOME                      1.0   357.0 NaN   357.0   357.0   357.0
64 PYRENEES-AT                      1.0   632.0 NaN   632.0   632.0   632.0
65 PYRENEES(HTE)                    1.0   164.0 NaN   164.0   164.0   164.0
66 PYRENEES-OR                      1.0  2619.0 NaN  2619.0  2619.0  2619.0
67 RHIN(BAS)                        1.0  1779.0 NaN  1779.0  1779.0  1779.0
68 RHIN (HAUT)                      1.0  2287.0 NaN  2287.0  2287.0  2287.0
69 RHONE                            1.0  2509.0 NaN  2509.0  2509.0  2509.0
70 SAONE(HAUTE)                     1.0    88.0 NaN    88.0    88.0    88.0
71 SAONE-ET-L                       1.0  1882.0 NaN  1882.0  1882.0  1882.0
72 SARTHE                           1.0    76.0 NaN    76.0    76.0    76.0
73 SAVOIE                           1.0   489.0 NaN   489.0   489.0   489.0
74 SAVOIE(HTE)                      1.0    93.0 NaN    93.0    93.0    93.0
77 SEINE ET MARNE                   1.0     9.0 NaN     9.0     9.0     9.0
79 SEVRES(DEUX)                     1.0   447.0 NaN   447.0   447.0   447.0
81 TARN                             1.0   598.0 NaN   598.0   598.0   598.0
82 TARN-ET-G                        1.0   345.0 NaN   345.0   345.0   345.0
83 VAR                              1.0  3448.0 NaN  3448.0  3448.0  3448.0
84 VAUCLUSE                         1.0  3926.0 NaN  3926.0  3926.0  3926.0
85 VENDEE                           1.0   868.0 NaN   868.0   868.0   868.0
86 VIENNE                           1.0   860.0 NaN   860.0   860.0   860.0
87 VIENNE(HTE)                      1.0     3.0 NaN     3.0     3.0     3.0
88 VOSGES                           1.0    64.0 NaN    64.0    64.0    64.0
89 YONNE                            1.0   849.0 NaN   849.0   849.0   849.0

                                  Sup totale vignes (ha)               \
                      75%     max                  count         mean
DEPARTEMENTS
01 AIN              321.0   321.0                    1.0     777.9424
02 AISNE            780.0   780.0                    1.0    2428.5932
03 ALLIER           134.0   134.0                    1.0     609.5174
04 ALPES-HTE-PR      69.0    69.0                    1.0     777.9662
05 ALPES-HAUTES     110.0   110.0                    1.0     137.7478
06 ALPES-Mmes        43.0    43.0                    1.0      84.2605
07 ARDECHE         1751.0  1751.0                    1.0   10436.2032
09 ARIEGE            29.0    29.0                    1.0      63.7400
10 AUBE            2582.0  2582.0                    1.0    7091.3031
11 AUDE            5408.0  5408.0                    1.0   64370.1712
12 AVEYRON          143.0   143.0                    1.0     454.1189
13 BOUCHES-DU-R    1133.0  1133.0                    1.0   10312.7723
14 CALVADOS           1.0     1.0                    1.0       4.9000
15 CANTAL             6.0     6.0                    1.0       7.5805
16 CHARENTE        2844.0  2844.0                    1.0   39155.4221
17 CHARENTE-MAR    3877.0  3877.0                    1.0   38924.3041
18 CHER             550.0   550.0                    1.0    4169.5045
19 CORREZE          239.0   239.0                    1.0     127.4322
21 COTE D'OR       1490.0  1490.0                    1.0    9669.4915
24 DORDOGNE        1296.0  1296.0                    1.0   11514.4276
25 DOUBS             57.0    57.0                    1.0      76.8496
26 DROME           1635.0  1635.0                    1.0   16040.7866
28 EURE-ET-LOIR       1.0     1.0                    1.0       0.1000
2A CORSE SUD         47.0    47.0                    1.0     875.1559
2B CORSE(HTE)       233.0   233.0                    1.0    4973.5197
30 GARD            3924.0  3924.0                    1.0   52490.5387
31 GARONNE(HTE)     252.0   252.0                    1.0    1492.3053
32 GERS            1240.0  1240.0                    1.0   18172.3389
33 GIRONDE         6662.0  6662.0                    1.0  114074.2247
34 HERAULT         8844.0  8844.0                    1.0   81058.6513
...                   ...     ...                    ...          ...
54 MEURTHE-&-M       57.0    57.0                    1.0     109.5516
55 MEUSE              7.0     7.0                    1.0      39.0693
57 MOSELLE           37.0    37.0                    1.0      97.8704
58 NIEVRE           257.0   257.0                    1.0    1520.2205
59 NORD               2.0     2.0                    1.0       0.6500
60 OISE               1.0     1.0                    1.0       0.2525
62 PAS-DE-CALAIS      1.0     1.0                    1.0       0.3000
63 PUY-DE-DOME      357.0   357.0                    1.0     439.1309
64 PYRENEES-AT      632.0   632.0                    1.0    2493.0711
65 PYRENEES(HTE)    164.0   164.0                    1.0     461.8576
66 PYRENEES-OR     2619.0  2619.0                    1.0   25720.6189
67 RHIN(BAS)       1779.0  1779.0                    1.0    6615.1147
68 RHIN (HAUT)     2287.0  2287.0                    1.0    8915.7324
69 RHONE           2509.0  2509.0                    1.0   16703.7113
70 SAONE(HAUTE)      88.0    88.0                    1.0    1243.0432
71 SAONE-ET-L      1882.0  1882.0                    1.0   12863.9952
72 SARTHE            76.0    76.0                    1.0     191.7419
73 SAVOIE           489.0   489.0                    1.0    1878.2255
74 SAVOIE(HTE)       93.0    93.0                    1.0     241.9473
77 SEINE ET MARNE     9.0     9.0                    1.0      21.6208
79 SEVRES(DEUX)     447.0   447.0                    1.0     803.7813
81 TARN             598.0   598.0                    1.0    6547.1526
82 TARN-ET-G        345.0   345.0                    1.0    1497.1505
83 VAR             3448.0  3448.0                    1.0   27933.8829
84 VAUCLUSE        3926.0  3926.0                    1.0   50316.4610
85 VENDEE           868.0   868.0                    1.0     976.9294
86 VIENNE           860.0   860.0                    1.0    1223.6586
87 VIENNE(HTE)        3.0     3.0                    1.0       6.6420
88 VOSGES            64.0    64.0                    1.0       8.5416
89 YONNE            849.0   849.0                    1.0    7513.5881

                     ...     Prod commercialisable (hl)              \
                     ...                            75%         max
DEPARTEMENTS         ...
01 AIN               ...                       45119.90    45119.90
02 AISNE             ...                      148195.13   148195.13
03 ALLIER            ...                       24963.80    24963.80
04 ALPES-HTE-PR      ...                       42539.38    42539.38
05 ALPES-HAUTES      ...                        5899.26     5899.26
06 ALPES-Mmes        ...                        2551.86     2551.86
07 ARDECHE           ...                      662857.14   662857.14
09 ARIEGE            ...                        2368.66     2368.66
10 AUBE              ...                      328822.04   328822.04
11 AUDE              ...                     3531155.59  3531155.59
12 AVEYRON           ...                       16062.02    16062.02
13 BOUCHES-DU-R      ...                      573442.04   573442.04
14 CALVADOS          ...                         132.95      132.95
15 CANTAL            ...                         174.50      174.50
16 CHARENTE          ...                     3664917.16  3664917.16
17 CHARENTE-MAR      ...                     4152625.85  4152625.85
18 CHER              ...                      202712.15   202712.15
19 CORREZE           ...                        3323.31     3323.31
21 COTE D'OR         ...                      270777.06   270777.06
24 DORDOGNE          ...                      612239.33   612239.33
25 DOUBS             ...                        1426.23     1426.23
26 DROME             ...                      817872.57   817872.57
28 EURE-ET-LOIR      ...                           6.60        6.60
2A CORSE SUD         ...                       37498.89    37498.89
2B CORSE(HTE)        ...                      341308.51   341308.51
30 GARD              ...                     3381878.34  3381878.34
31 GARONNE(HTE)      ...                       93622.70    93622.70
32 GERS              ...                     1893399.66  1893399.66
33 GIRONDE           ...                     6340333.11  6340333.11
34 HERAULT           ...                     4530968.40  4530968.40
...                  ...                            ...         ...
54 MEURTHE-&-M       ...                        5243.26     5243.26
55 MEUSE             ...                        2187.20     2187.20
57 MOSELLE           ...                        2541.24     2541.24
58 NIEVRE            ...                       55809.41    55809.41
59 NORD              ...                           2.90        2.90
60 OISE              ...                           9.00        9.00
62 PAS-DE-CALAIS     ...                           4.20        4.20
63 PUY-DE-DOME       ...                       16263.91    16263.91
64 PYRENEES-AT       ...                      111872.37   111872.37
65 PYRENEES(HTE)     ...                       11780.45    11780.45
66 PYRENEES-OR       ...                      660939.68   660939.68
67 RHIN(BAS)         ...                      509568.80   509568.80
68 RHIN (HAUT)       ...                      676321.13   676321.13
69 RHONE             ...                      809664.81   809664.81
70 SAONE(HAUTE)      ...                        2173.74     2173.74
71 SAONE-ET-L        ...                      735117.44   735117.44
72 SARTHE            ...                        3515.56     3515.56
73 SAVOIE            ...                      117178.91   117178.91
74 SAVOIE(HTE)       ...                       14071.28    14071.28
77 SEINE ET MARNE    ...                        1395.38     1395.38
79 SEVRES(DEUX)      ...                       45656.26    45656.26
81 TARN              ...                      476121.39   476121.39
82 TARN-ET-G         ...                      104440.87   104440.87
83 VAR               ...                     1416479.67  1416479.67
84 VAUCLUSE          ...                     2144396.86  2144396.86
85 VENDEE            ...                       34864.66    34864.66
86 VIENNE            ...                       56688.41    56688.41
87 VIENNE(HTE)       ...                          94.00       94.00
88 VOSGES            ...                          73.90       73.90
89 YONNE             ...                      205464.96   205464.96

                  Prod non commercialisable (hl)                            \
                                           count       mean std        min
DEPARTEMENTS
01 AIN                                       1.0     314.83 NaN     314.83
02 AISNE                                     1.0    9149.60 NaN    9149.60
03 ALLIER                                    1.0     536.62 NaN     536.62
04 ALPES-HTE-PR                              1.0    1177.17 NaN    1177.17
05 ALPES-HAUTES                              1.0     408.74 NaN     408.74
06 ALPES-Mmes                                1.0      40.90 NaN      40.90
07 ARDECHE                                   1.0   14450.37 NaN   14450.37
09 ARIEGE                                    1.0      31.88 NaN      31.88
10 AUBE                                      1.0    9282.96 NaN    9282.96
11 AUDE                                      1.0   56656.43 NaN   56656.43
12 AVEYRON                                   1.0     536.01 NaN     536.01
13 BOUCHES-DU-R                              1.0   21251.08 NaN   21251.08
14 CALVADOS                                  1.0       0.00 NaN       0.00
15 CANTAL                                    1.0       5.50 NaN       5.50
16 CHARENTE                                  1.0    4054.81 NaN    4054.81
17 CHARENTE-MAR                              1.0    8540.52 NaN    8540.52
18 CHER                                      1.0     456.73 NaN     456.73
19 CORREZE                                   1.0       0.93 NaN       0.93
21 COTE D'OR                                 1.0    3089.36 NaN    3089.36
24 DORDOGNE                                  1.0   24597.13 NaN   24597.13
25 DOUBS                                     1.0      16.00 NaN      16.00
26 DROME                                     1.0   30480.90 NaN   30480.90
28 EURE-ET-LOIR                              1.0       0.00 NaN       0.00
2A CORSE SUD                                 1.0    1053.16 NaN    1053.16
2B CORSE(HTE)                                1.0    8876.82 NaN    8876.82
30 GARD                                      1.0   87823.75 NaN   87823.75
31 GARONNE(HTE)                              1.0    2327.50 NaN    2327.50
32 GERS                                      1.0   30846.86 NaN   30846.86
33 GIRONDE                                   1.0  367346.69 NaN  367346.69
34 HERAULT                                   1.0   98613.87 NaN   98613.87
...                                          ...        ...  ..        ...
54 MEURTHE-&-M                               1.0      57.08 NaN      57.08
55 MEUSE                                     1.0      66.40 NaN      66.40
57 MOSELLE                                   1.0       7.60 NaN       7.60
58 NIEVRE                                    1.0      15.63 NaN      15.63
59 NORD                                      1.0       0.00 NaN       0.00
60 OISE                                      1.0       0.00 NaN       0.00
62 PAS-DE-CALAIS                             1.0       0.00 NaN       0.00
63 PUY-DE-DOME                               1.0     168.55 NaN     168.55
64 PYRENEES-AT                               1.0    4754.18 NaN    4754.18
65 PYRENEES(HTE)                             1.0     622.22 NaN     622.22
66 PYRENEES-OR                               1.0   14236.28 NaN   14236.28
67 RHIN(BAS)                                 1.0   30715.40 NaN   30715.40
68 RHIN (HAUT)                               1.0   38021.14 NaN   38021.14
69 RHONE                                     1.0   42480.04 NaN   42480.04
70 SAONE(HAUTE)                              1.0       0.00 NaN       0.00
71 SAONE-ET-L                                1.0   22190.45 NaN   22190.45
72 SARTHE                                    1.0      88.18 NaN      88.18
73 SAVOIE                                    1.0    2117.92 NaN    2117.92
74 SAVOIE(HTE)                               1.0      43.49 NaN      43.49
77 SEINE ET MARNE                            1.0      41.70 NaN      41.70
79 SEVRES(DEUX)                              1.0     640.11 NaN     640.11
81 TARN                                      1.0    9602.99 NaN    9602.99
82 TARN-ET-G                                 1.0    2611.25 NaN    2611.25
83 VAR                                       1.0   53107.81 NaN   53107.81
84 VAUCLUSE                                  1.0   64904.33 NaN   64904.33
85 VENDEE                                    1.0     735.86 NaN     735.86
86 VIENNE                                    1.0     475.24 NaN     475.24
87 VIENNE(HTE)                               1.0      10.00 NaN      10.00
88 VOSGES                                    1.0       0.00 NaN       0.00
89 YONNE                                     1.0    1247.05 NaN    1247.05


                         25%        50%        75%        max
DEPARTEMENTS
01 AIN                314.83     314.83     314.83     314.83
02 AISNE             9149.60    9149.60    9149.60    9149.60
03 ALLIER             536.62     536.62     536.62     536.62
04 ALPES-HTE-PR      1177.17    1177.17    1177.17    1177.17
05 ALPES-HAUTES       408.74     408.74     408.74     408.74
06 ALPES-Mmes          40.90      40.90      40.90      40.90
07 ARDECHE          14450.37   14450.37   14450.37   14450.37
09 ARIEGE              31.88      31.88      31.88      31.88
10 AUBE              9282.96    9282.96    9282.96    9282.96
11 AUDE             56656.43   56656.43   56656.43   56656.43
12 AVEYRON            536.01     536.01     536.01     536.01
13 BOUCHES-DU-R     21251.08   21251.08   21251.08   21251.08
14 CALVADOS             0.00       0.00       0.00       0.00
15 CANTAL               5.50       5.50       5.50       5.50
16 CHARENTE          4054.81    4054.81    4054.81    4054.81
17 CHARENTE-MAR      8540.52    8540.52    8540.52    8540.52
18 CHER               456.73     456.73     456.73     456.73
19 CORREZE              0.93       0.93       0.93       0.93
21 COTE D'OR         3089.36    3089.36    3089.36    3089.36
24 DORDOGNE         24597.13   24597.13   24597.13   24597.13
25 DOUBS               16.00      16.00      16.00      16.00
26 DROME            30480.90   30480.90   30480.90   30480.90
28 EURE-ET-LOIR         0.00       0.00       0.00       0.00
2A CORSE SUD         1053.16    1053.16    1053.16    1053.16
2B CORSE(HTE)        8876.82    8876.82    8876.82    8876.82
30 GARD             87823.75   87823.75   87823.75   87823.75

In [48]:
production2017.groupby('DEPARTEMENTS').describe()

                            Nb déclarations prod                               \
                                            count    mean std     min     25%
DEPARTEMENTS
01 AIN                                        1.0   284.0 NaN   284.0   284.0
02 AISNE                                      1.0   818.0 NaN   818.0   818.0
03 ALLIER                                     1.0   109.0 NaN   109.0   109.0
04 ALPES DE HAUTES-PROVENCE                   1.0    72.0 NaN    72.0    72.0
05 HAUTES-ALPES                               1.0    94.0 NaN    94.0    94.0
06 ALPES-MARITIMES                            1.0    24.0 NaN    24.0    24.0
07 ARDECHE                                    1.0  1610.0 NaN  1610.0  1610.0
09 ARIEGE                                     1.0    25.0 NaN    25.0    25.0
10 AUBE                                       1.0  2605.0 NaN  2605.0  2605.0
11 AUDE                                       1.0  5282.0 NaN  5282.0  5282.0
12 AVEYRON                                    1.0   132.0 NaN   132.0   132.0
13 BOUCHES-DU-RHONE                           1.0  1151.0 NaN  1151.0  1151.0
14 CALVADOS                                   1.0     1.0 NaN     1.0     1.0
15 CANTAL                                     1.0     6.0 NaN     6.0     6.0
16 CHARENTE                                   1.0  2729.0 NaN  2729.0  2729.0
17 CHARENTE-MARITIME                          1.0  3719.0 NaN  3719.0  3719.0
18 CHER                                       1.0   538.0 NaN   538.0   538.0
19 CORREZE                                    1.0   166.0 NaN   166.0   166.0
21 COTE-D'OR                                  1.0  1451.0 NaN  1451.0  1451.0
24 DORDOGNE                                   1.0  1062.0 NaN  1062.0  1062.0
25 DOUBS                                      1.0    68.0 NaN    68.0    68.0
26 DROME                                      1.0  1590.0 NaN  1590.0  1590.0
28 EURE-ET-LOIR                               1.0     0.0 NaN     0.0     0.0
2A CORSE-DU-SUD                               1.0    47.0 NaN    47.0    47.0
2B HAUTE-CORSE                                1.0   229.0 NaN   229.0   229.0
30 GARD                                       1.0  3915.0 NaN  3915.0  3915.0
31 HAUTE-GARONNE                              1.0   166.0 NaN   166.0   166.0
32 GERS                                       1.0  1154.0 NaN  1154.0  1154.0
33 GIRONDE                                    1.0  6452.0 NaN  6452.0  6452.0
34 HERAULT                                    1.0  8575.0 NaN  8575.0  8575.0
...                                           ...     ...  ..     ...     ...
57 MOSELLE                                    1.0    33.0 NaN    33.0    33.0
58 NIEVRE                                     1.0   254.0 NaN   254.0   254.0
59 NORD                                       1.0     1.0 NaN     1.0     1.0
60 OISE                                       1.0     1.0 NaN     1.0     1.0
62 PAS-DE-CALAIS                              1.0     1.0 NaN     1.0     1.0
63 PUY-DE-DOME                                1.0   299.0 NaN   299.0   299.0
64 PYRENEES-ATLANTIQUES                       1.0   588.0 NaN   588.0   588.0
65 HAUTES-PYRENEES                            1.0   113.0 NaN   113.0   113.0
66 PYRENEES-ORIENTALES                        1.0  2509.0 NaN  2509.0  2509.0
67 BAS-RHIN                                   1.0  1729.0 NaN  1729.0  1729.0
68 HAUT-RHIN                                  1.0  2230.0 NaN  2230.0  2230.0
69 RHONE                                      1.0  2411.0 NaN  2411.0  2411.0
70 HAUTE-SAONE                                1.0    94.0 NaN    94.0    94.0
71 SAONE-ET-LOIRE                             1.0  1825.0 NaN  1825.0  1825.0
72 SARTHE                                     1.0    64.0 NaN    64.0    64.0
73 SAVOIE                                     1.0   420.0 NaN   420.0   420.0
74 HAUTE-SAVOIE                               1.0    82.0 NaN    82.0    82.0
76 SEINE-MARITIME                             1.0     1.0 NaN     1.0     1.0
77 SEINE-ET-MARNE                             1.0     9.0 NaN     9.0     9.0
79 DEUX-SEVRES                                1.0   338.0 NaN   338.0   338.0
81 TARN                                       1.0   557.0 NaN   557.0   557.0
82 TARN-ET-GARONNE                            1.0   288.0 NaN   288.0   288.0
83 VAR                                        1.0  3356.0 NaN  3356.0  3356.0
84 VAUCLUSE                                   1.0  3829.0 NaN  3829.0  3829.0
85 VENDEE                                     1.0   632.0 NaN   632.0   632.0
86 VIENNE                                     1.0   667.0 NaN   667.0   667.0
87 HAUTE-VIENNE                               1.0     2.0 NaN     2.0     2.0
88 VOSGES                                     1.0    54.0 NaN    54.0    54.0
89 YONNE                                      1.0   860.0 NaN   860.0   860.0
90 TERRITOIRE-DE-BELFORT                      1.0     1.0 NaN     1.0     1.0

                                                    Sup totale vignes (ha)  \
                                50%     75%     max                  count
DEPARTEMENTS
01 AIN                        284.0   284.0   284.0                    1.0
02 AISNE                      818.0   818.0   818.0                    1.0
03 ALLIER                     109.0   109.0   109.0                    1.0
04 ALPES DE HAUTES-PROVENCE    72.0    72.0    72.0                    1.0
05 HAUTES-ALPES                94.0    94.0    94.0                    1.0
06 ALPES-MARITIMES             24.0    24.0    24.0                    1.0
07 ARDECHE                   1610.0  1610.0  1610.0                    1.0
09 ARIEGE                      25.0    25.0    25.0                    1.0
10 AUBE                      2605.0  2605.0  2605.0                    1.0
11 AUDE                      5282.0  5282.0  5282.0                    1.0
12 AVEYRON                    132.0   132.0   132.0                    1.0
13 BOUCHES-DU-RHONE          1151.0  1151.0  1151.0                    1.0
14 CALVADOS                     1.0     1.0     1.0                    1.0
15 CANTAL                       6.0     6.0     6.0                    1.0
16 CHARENTE                  2729.0  2729.0  2729.0                    1.0
17 CHARENTE-MARITIME         3719.0  3719.0  3719.0                    1.0
18 CHER                       538.0   538.0   538.0                    1.0
19 CORREZE                    166.0   166.0   166.0                    1.0
21 COTE-D'OR                 1451.0  1451.0  1451.0                    1.0
24 DORDOGNE                  1062.0  1062.0  1062.0                    1.0
25 DOUBS                       68.0    68.0    68.0                    1.0
26 DROME                     1590.0  1590.0  1590.0                    1.0
28 EURE-ET-LOIR                 0.0     0.0     0.0                    1.0
2A CORSE-DU-SUD                47.0    47.0    47.0                    1.0
2B HAUTE-CORSE                229.0   229.0   229.0                    1.0
30 GARD                      3915.0  3915.0  3915.0                    1.0
31 HAUTE-GARONNE              166.0   166.0   166.0                    1.0
32 GERS                      1154.0  1154.0  1154.0                    1.0
33 GIRONDE                   6452.0  6452.0  6452.0                    1.0
34 HERAULT                   8575.0  8575.0  8575.0                    1.0
...                             ...     ...     ...                    ...
57 MOSELLE                     33.0    33.0    33.0                    1.0
58 NIEVRE                     254.0   254.0   254.0                    1.0
59 NORD                         1.0     1.0     1.0                    1.0
60 OISE                         1.0     1.0     1.0                    1.0
62 PAS-DE-CALAIS                1.0     1.0     1.0                    1.0
63 PUY-DE-DOME                299.0   299.0   299.0                    1.0
64 PYRENEES-ATLANTIQUES       588.0   588.0   588.0                    1.0
65 HAUTES-PYRENEES            113.0   113.0   113.0                    1.0
66 PYRENEES-ORIENTALES       2509.0  2509.0  2509.0                    1.0
67 BAS-RHIN                  1729.0  1729.0  1729.0                    1.0
68 HAUT-RHIN                 2230.0  2230.0  2230.0                    1.0
69 RHONE                     2411.0  2411.0  2411.0                    1.0
70 HAUTE-SAONE                 94.0    94.0    94.0                    1.0
71 SAONE-ET-LOIRE            1825.0  1825.0  1825.0                    1.0
72 SARTHE                      64.0    64.0    64.0                    1.0
73 SAVOIE                     420.0   420.0   420.0                    1.0
74 HAUTE-SAVOIE                82.0    82.0    82.0                    1.0
76 SEINE-MARITIME               1.0     1.0     1.0                    1.0
77 SEINE-ET-MARNE               9.0     9.0     9.0                    1.0
79 DEUX-SEVRES                338.0   338.0   338.0                    1.0
81 TARN                       557.0   557.0   557.0                    1.0
82 TARN-ET-GARONNE            288.0   288.0   288.0                    1.0
83 VAR                       3356.0  3356.0  3356.0                    1.0
84 VAUCLUSE                  3829.0  3829.0  3829.0                    1.0
85 VENDEE                     632.0   632.0   632.0                    1.0
86 VIENNE                     667.0   667.0   667.0                    1.0
87 HAUTE-VIENNE                 2.0     2.0     2.0                    1.0
88 VOSGES                      54.0    54.0    54.0                    1.0
89 YONNE                      860.0   860.0   860.0                    1.0
90 TERRITOIRE-DE-BELFORT        1.0     1.0     1.0                    1.0

                                            ...      \
                                    mean    ...
DEPARTEMENTS                                ...
01 AIN                          749.5860    ...
02 AISNE                       2523.6857    ...
03 ALLIER                       610.2514    ...
04 ALPES DE HAUTES-PROVENCE     700.5272    ...
05 HAUTES-ALPES                 114.6767    ...
06 ALPES-MARITIMES               83.9044    ...
07 ARDECHE                    10273.6524    ...
09 ARIEGE                        67.4368    ...
10 AUBE                        7171.9611    ...
11 AUDE                       64535.0459    ...
12 AVEYRON                      388.5481    ...
13 BOUCHES-DU-RHONE           11192.9550    ...
14 CALVADOS                       4.9000    ...
15 CANTAL                         9.2560    ...
16 CHARENTE                   39336.9834    ...
17 CHARENTE-MARITIME          39102.3830    ...
18 CHER                        4225.6395    ...
19 CORREZE                       93.9789    ...
21 COTE-D'OR                   9464.9361    ...
24 DORDOGNE                   11311.3471    ...
25 DOUBS                         25.9804    ...
26 DROME                      15864.8640    ...
28 EURE-ET-LOIR                   0.0000    ...
2A CORSE-DU-SUD                 876.9278    ...
2B HAUTE-CORSE                 5000.3120    ...
30 GARD                       52604.6921    ...
31 HAUTE-GARONNE               1359.1508    ...
32 GERS                       18476.8786    ...
33 GIRONDE                   114554.3782    ...
34 HERAULT                    80840.5254    ...
...                                  ...    ...
57 MOSELLE                       77.8164    ...
58 NIEVRE                      1527.6356    ...
59 NORD                           1.1600    ...
60 OISE                           0.2525    ...
62 PAS-DE-CALAIS                  0.3000    ...
63 PUY-DE-DOME                  438.4123    ...
64 PYRENEES-ATLANTIQUES        2499.7498    ...
65 HAUTES-PYRENEES              250.5922    ...
66 PYRENEES-ORIENTALES        21437.6506    ...
67 BAS-RHIN                    6698.0237    ...
68 HAUT-RHIN                   8986.9572    ...
69 RHONE                      16237.0183    ...
70 HAUTE-SAONE                  103.9686    ...
71 SAONE-ET-LOIRE             12990.8598    ...
72 SARTHE                       197.9071    ...
73 SAVOIE                      1849.6304    ...
74 HAUTE-SAVOIE                 239.9497    ...
76 SEINE-MARITIME                 0.6000    ...
77 SEINE-ET-MARNE                26.6895    ...
79 DEUX-SEVRES                  810.4565    ...
81 TARN                        6560.6776    ...
82 TARN-ET-GARONNE             1473.9493    ...
83 VAR                        28110.8926    ...
84 VAUCLUSE                   45748.9434    ...
85 VENDEE                       949.6227    ...
86 VIENNE                      1186.8673    ...
87 HAUTE-VIENNE                   7.1386    ...
88 VOSGES                         7.2618    ...
89 YONNE                       7683.4878    ...
90 TERRITOIRE-DE-BELFORT          0.2500    ...

                            Prod commercialisable (hl)              \
                                                   75%         max
DEPARTEMENTS
01 AIN                                        29429.25    29429.25
02 AISNE                                     151224.19   151224.19
03 ALLIER                                     14783.62    14783.62
04 ALPES DE HAUTES-PROVENCE                   32118.58    32118.58
05 HAUTES-ALPES                                2063.21     2063.21
06 ALPES-MARITIMES                             2054.05     2054.05
07 ARDECHE                                   389257.84   389257.84
09 ARIEGE                                      1319.90     1319.90
10 AUBE                                      485952.56   485952.56
11 AUDE                                     3093722.02  3093722.02
12 AVEYRON                                     4716.69     4716.69
13 BOUCHES-DU-RHONE                          516954.91   516954.91
14 CALVADOS                                     116.65      116.65
15 CANTAL                                       101.85      101.85
16 CHARENTE                                 3018900.86  3018900.86
17 CHARENTE-MARITIME                        3830758.77  3830758.77
18 CHER                                      234903.76   234903.76
19 CORREZE                                     1091.37     1091.37
21 COTE-D'OR                                 460596.83   460596.83
24 DORDOGNE                                  300026.60   300026.60
25 DOUBS                                        619.50      619.50
26 DROME                                     568663.69   568663.69
28 EURE-ET-LOIR                                   0.00        0.00
2A CORSE-DU-SUD                               26718.22    26718.22
2B HAUTE-CORSE                               281301.31   281301.31
30 GARD                                     2515072.32  2515072.32
31 HAUTE-GARONNE                              46550.38    46550.38
32 GERS                                     1592374.22  1592374.22
33 GIRONDE                                  3573449.06  3573449.06
34 HERAULT                                  3930368.86  3930368.86
...                                                ...         ...
57 MOSELLE                                     2927.77     2927.77
58 NIEVRE                                     73216.75    73216.75
59 NORD                                          39.75       39.75
60 OISE                                          11.50       11.50
62 PAS-DE-CALAIS                                  7.00        7.00
63 PUY-DE-DOME                                10171.57    10171.57
64 PYRENEES-ATLANTIQUES                      101575.87   101575.87
65 HAUTES-PYRENEES                            11017.50    11017.50
66 PYRENEES-ORIENTALES                       656138.70   656138.70
67 BAS-RHIN                                  432839.32   432839.32
68 HAUT-RHIN                                 479292.55   479292.55
69 RHONE                                     637590.67   637590.67
70 HAUTE-SAONE                                 2852.35     2852.35
71 SAONE-ET-LOIRE                            700909.27   700909.27
72 SARTHE                                      6159.45     6159.45
73 SAVOIE                                     96427.32    96427.32
74 HAUTE-SAVOIE                                8365.83     8365.83
76 SEINE-MARITIME                                15.70       15.70
77 SEINE-ET-MARNE                              1356.60     1356.60
79 DEUX-SEVRES                                40540.50    40540.50
81 TARN                                      356615.06   356615.06
82 TARN-ET-GARONNE                            60088.56    60088.56
83 VAR                                      1157279.19  1157279.19
84 VAUCLUSE                                 1504177.90  1504177.90
85 VENDEE                                     43745.71    43745.71
86 VIENNE                                     49942.96    49942.96
87 HAUTE-VIENNE                                  30.90       30.90
88 VOSGES                                       181.80      181.80
89 YONNE                                     345123.07   345123.07
90 TERRITOIRE-DE-BELFORT                         20.00       20.00

                            Autres production (hl)                            \
                                             count       mean std        min
DEPARTEMENTS
01 AIN                                         1.0     186.12 NaN     186.12
02 AISNE                                       1.0    1341.88 NaN    1341.88
03 ALLIER                                      1.0     282.28 NaN     282.28
04 ALPES DE HAUTES-PROVENCE                    1.0     934.01 NaN     934.01
05 HAUTES-ALPES                                1.0     131.46 NaN     131.46
06 ALPES-MARITIMES                             1.0      40.00 NaN      40.00
07 ARDECHE                                     1.0    7346.63 NaN    7346.63
09 ARIEGE                                      1.0      30.21 NaN      30.21
10 AUBE                                        1.0    7408.31 NaN    7408.31
11 AUDE                                        1.0   53372.40 NaN   53372.40
12 AVEYRON                                     1.0     151.54 NaN     151.54
13 BOUCHES-DU-RHONE                            1.0   18490.51 NaN   18490.51
14 CALVADOS                                    1.0       0.00 NaN       0.00
15 CANTAL                                      1.0       3.70 NaN       3.70
16 CHARENTE                                    1.0    3316.71 NaN    3316.71
17 CHARENTE-MARITIME                           1.0    9586.67 NaN    9586.67
18 CHER                                        1.0    1087.37 NaN    1087.37
19 CORREZE                                     1.0      10.04 NaN      10.04
21 COTE-D'OR                                   1.0    7711.14 NaN    7711.14
24 DORDOGNE                                    1.0    6160.47 NaN    6160.47
25 DOUBS                                       1.0      34.53 NaN      34.53
26 DROME                                       1.0   13762.15 NaN   13762.15
28 EURE-ET-LOIR                                1.0       0.00 NaN       0.00
2A CORSE-DU-SUD                                1.0     745.53 NaN     745.53
2B HAUTE-CORSE                                 1.0    6215.86 NaN    6215.86
30 GARD                                        1.0   68538.32 NaN   68538.32
31 HAUTE-GARONNE                               1.0    1302.12 NaN    1302.12
32 GERS                                        1.0   69611.85 NaN   69611.85
33 GIRONDE                                     1.0   64812.28 NaN   64812.28
34 HERAULT                                     1.0  106111.31 NaN  106111.31
...                                            ...        ...  ..        ...
57 MOSELLE                                     1.0      20.26 NaN      20.26
58 NIEVRE                                      1.0     786.14 NaN     786.14
59 NORD                                        1.0       0.00 NaN       0.00
60 OISE                                        1.0       0.00 NaN       0.00
62 PAS-DE-CALAIS                               1.0       0.00 NaN       0.00

In [49]:
prod2015 = production2015.copy()
prod2016 = production2016.copy()
prod2017 = production2017.copy()

In [50]:
prod2015['Total Blanc'] = prod2015.apply( lambda row : (row["Qt AOP Blanc (hl)"] + row["Qt IGP Blanc (hl)"]+ row["Qt VSIG Blanc (hl)"]), axis = 1 ) 
prod2015['Total Rouge'] = prod2015.apply( lambda row : (row["Qt AOP Rouge (hl)"] + row["Qt IGP Rouge (hl)"]+ row["Qt VSIG Rouge (hl)"]), axis = 1 ) 
prod2015['Total Rosé'] = prod2015.apply( lambda row : (row["Qt AOP Rosé (hl)"] + row["Qt IGP Rosé (hl)"]+ row["Qt VSIG Rosé (hl)"]), axis = 1 ) 
prod2015['Total Prod'] = prod2015.apply( lambda row : (row["Prod commercialisable (hl)"] + row["Prod non commercialisable (hl)"]), axis = 1 ) 
prod2015.head(1)

,Nb déclarations prod,Sup totale vignes (ha),Sup vignes AOP (ha),Sup vignes cognac - armagniac (ha),Sup vignes IGP (ha),Sup vignes VSIG (ha),Qt AOP Blanc (hl),Qt AOP Rouge (hl),Qt AOP Rosé (hl),Qt AOP VSI/VCI (hl),...,Qt VSIG Blanc (hl),Qt VSIG Rouge (hl),Qt VSIG Rosé (hl),Qt Cognac ou Armagnec (hl),Prod commercialisable (hl),Prod non commercialisable (hl),Total Blanc,Total Rouge,Total Rosé,Total Prod
DEPARTEMENTS,,,,,,,,,,,,,,,,,,,,,
01 AIN,382,758.4526,551.8399,0.0,17.2905,189.3222,12323.03,2897.22,12658.4,0.0,...,2977.2,1672.51,5846.95,0.0,38988.92,244.4,15742.94,4649.58,18596.4,39233.32

In [51]:
prod2016['Total Blanc'] = prod2016.apply( lambda row : (row["Qt AOP Blanc (hl)"] + row["Qt IGP Blanc (hl)"]+ row["Qt VSIG Blanc (hl)"]), axis = 1 ) 
prod2016['Total Rouge'] = prod2016.apply( lambda row : (row["Qt AOP Rouge (hl)"] + row["Qt IGP Rouge (hl)"]+ row["Qt VSIG Rouge (hl)"]), axis = 1 ) 
prod2016['Total Rosé'] = prod2016.apply( lambda row : (row["Qt AOP Rosé (hl)"] + row["Qt IGP Rosé (hl)"]+ row["Qt VSIG Rosé (hl)"]), axis = 1 ) 
prod2016['Total Prod'] = prod2016.apply( lambda row : (row["Prod commercialisable (hl)"] + row["Prod non commercialisable (hl)"]), axis = 1 ) 
prod2016.head(1)

,Nb déclarations prod,Sup totale vignes (ha),Sup vignes AOP (ha),Sup vignes cognac - armagniac (ha),Sup vignes IGP (ha),Sup vignes VSIG (ha),Qt AOP Blanc (hl),Qt AOP Rouge (hl),Qt AOP Rosé (hl),Qt AOP VSI/VCI (hl),...,Qt VSIG Blanc (hl),Qt VSIG Rouge (hl),Qt VSIG Rosé (hl),Qt Cognac ou Armagnec (hl),Prod commercialisable (hl),Prod non commercialisable (hl),Total Blanc,Total Rouge,Total Rosé,Total Prod
DEPARTEMENTS,,,,,,,,,,,,,,,,,,,,,
01 AIN,321,777.9424,540.2316,0.0,19.9388,217.772,13283.93,2992.1,13615.22,0.0,...,4635.04,2137.33,7383.05,0.0,45119.9,314.83,18663.51,5266.12,21190.27,45434.73

In [52]:
prod2017['Total Blanc'] = prod2017.apply( lambda row : (row["Qt AOP Blanc (hl)"] + row["Qt IGP Blanc (hl)"]+ row["Qt VSIG Blanc (hl)"]), axis = 1 ) 
prod2017['Total Rouge'] = prod2017.apply( lambda row : (row["Qt AOP Rouge (hl)"] + row["Qt IGP Rouge (hl)"]+ row["Qt VSIG Rouge (hl)"]), axis = 1 ) 
prod2017['Total Rosé'] = prod2017.apply( lambda row : (row["Qt AOP Rosé (hl)"] + row["Qt IGP Rosé (hl)"]+ row["Qt VSIG Rosé (hl)"]), axis = 1 ) 
prod2017['Total Prod'] = prod2017.apply( lambda row : (row["Prod commercialisable (hl)"] + row["Autres production (hl)"]), axis = 1 ) 
prod2017.head(1)

,Nb déclarations prod,Sup totale vignes (ha),Sup vignes AOP (ha),Sup vignes cognac - armagniac (ha),Sup vignes IGP (ha),Sup vignes VSIG (ha),Qt AOP Blanc (hl),Qt AOP Rouge (hl),Qt AOP Rosé (hl),Qt AOP VSI/VCI (hl),...,Qt VSIG Blanc (hl),Qt VSIG Rouge (hl),Qt VSIG Rosé (hl),Qt Cognac ou Armagnec (hl),Prod commercialisable (hl),Autres production (hl),Total Blanc,Total Rouge,Total Rosé,Total Prod
DEPARTEMENTS,,,,,,,,,,,,,,,,,,,,,
01 AIN,284,749.586,537.0579,0.0,20.5849,191.9432,9457.75,2495.3,8143.25,0.0,...,3675.53,1639.45,3224.92,0.0,29429.25,186.12,13728.53,4266.35,11434.37,29615.37

In [53]:
prod2015 = prod2015.loc[:, ['Sup totale vignes (ha)', 'Qt Cognac ou Armagniac (hl)', 'Total Blanc', 'Total Rouge', 'Total Rosé', 'Total Prod']]
prod2015.head()

,Sup totale vignes (ha),Qt Cognac ou Armagnec (hl),Total Blanc,Total Rouge,Total Rosé,Total Prod
DEPARTEMENTS,,,,,,
01 AIN,758.4526,0.0,15742.94,4649.58,18596.40,39233.32
02 AISNE,2441.2928,0.0,165126.45,7.70,0.00,179477.20
03 ALLIER,647.2769,0.0,7941.74,13520.54,4961.57,27103.13
04 ALPES-HTE-PR,674.1128,0.0,4737.06,12285.97,23445.04,41732.62
05 ALPES-HAUTES,115.6571,0.0,966.45,2145.34,1062.23,4455.53

In [54]:
prod2016 = prod2016.loc[:, ['Sup totale vignes (ha)', 'Qt Cognac ou Armagniac (hl)', 'Total Blanc', 'Total Rouge', 'Total Rosé', 'Total Prod']]
prod2016.head()

,Sup totale vignes (ha),Qt Cognac ou Armagnec (hl),Total Blanc,Total Rouge,Total Rosé,Total Prod
DEPARTEMENTS,,,,,,
01 AIN,777.9424,0.0,18663.51,5266.12,21190.27,45434.73
02 AISNE,2428.5932,0.0,148195.13,0.00,0.00,157344.73
03 ALLIER,609.5174,0.0,7116.89,13476.39,4370.52,25500.42
04 ALPES-HTE-PR,777.9662,0.0,4889.75,12341.25,25308.38,43716.55
05 ALPES-HAUTES,137.7478,0.0,1647.57,2779.89,1471.80,6308.00

In [57]:
prod2017 = prod2017.loc[:, ['Sup totale vignes (ha)', 'Qt Cognac ou Armagniac (hl)', 'Total Blanc', 'Total Rouge', 'Total Rosé', 'Total Prod']]
prod2017.head()

,Sup totale vignes (ha),Qt Cognac ou Armagnec (hl),Total Blanc,Total Rouge,Total Rosé,Total Prod
DEPARTEMENTS,,,,,,
01 AIN,749.5860,0.0,13728.53,4266.35,11434.37,29615.37
02 AISNE,2523.6857,0.0,151224.19,0.00,0.00,152566.07
03 ALLIER,610.2514,0.0,3789.91,8391.70,2602.01,15065.90
04 ALPES DE HAUTES-PROVENCE,700.5272,0.0,4103.03,8901.13,19114.42,33052.59
05 HAUTES-ALPES,114.6767,0.0,405.38,1060.14,597.69,2194.67

In [60]:
prod2015.mean()

Sup totale vignes (ha)          9462.112778
Qt Cognac ou Armagnec (hl)    119986.771013
Total Blanc                   152321.745823
Total Rouge                   233112.562025
Total Rosé                     83993.693291
Total Prod                    605767.307215
dtype: float64

In [61]:
prod2016.mean()

Sup totale vignes (ha)          9798.355866
Qt Cognac ou Armagnec (hl)    100298.991558
Total Blanc                   148578.456623
Total Rouge                   241644.663377
Total Rosé                     80440.818831
Total Prod                    591716.016104
dtype: float64

In [62]:
prod2017.mean()

Sup totale vignes (ha)          9430.936034
Qt Cognac ou Armagnec (hl)     85975.751392
Total Blanc                   127855.432785
Total Rouge                   170933.163165
Total Rosé                     70915.688481
Total Prod                    465607.538861
dtype: float64

In [65]:
writer = pd.ExcelWriter('etudeVins.xlsx')
prod2015.to_excel(writer, 'Prod 2015')
prod2016.to_excel(writer, 'Prod 2016')
prod2017.to_excel(writer, 'Prod 2017')
writer.save()